matrix:
  include:
    - language: go
      go: 1.9
      sudo: required
      before_script: 
        - go get -t ./otc/...
        - cd otc
      script: 
        - go build
      after_success:
        - 
    - language: node_js
      node_js: 
        - "8"
      before_install:
        - npm install -g yarn --cache-min 999999999
      before_script: 
        - cd otc-web
        - yarn install
      script:
        - yarn build
    - language: node_js
      node_js: 
        - "8"
      before_install:
        - npm install -g yarn --cache-min 999999999
      before_script: 
        - cd otc-web-admin
        - yarn install
      script:
        - yarn build