matrix:
  include:
  - language: go
    go_import_path: github.com/skycoin/services
    go: 1.9
    sudo: required
    install: true
    script:
    - cd ./otc
    - go build
    deploy:
    - provider: script
      script:
      - sh $TRAVIS_BUILD_DIR/.travis/deploy.sh
      skip_cleanup: true
      on:
        repo: skycoin/services
  - language: node_js
    node_js:
    - '8'
    before_install:
    - npm install -g yarn --cache-min 999999999
    before_script:
    - cd otc-web
    - yarn install
    script:
    - yarn build
    deploy:
    - provider: script
      script:
      - sh $TRAVIS_BUILD_DIR/.travis/deploy.sh
      skip_cleanup: true
      on:
        repo: skycoin/services
  - language: node_js
    node_js:
    - '8'
    before_install:
    - npm install -g yarn --cache-min 999999999
    before_script:
    - cd otc-web-admin
    - yarn install
    script:
    - yarn build
    deploy:
    - provider: script
      script:
      - sh $TRAVIS_BUILD_DIR/.travis/deploy.sh
      skip_cleanup: true
      on:
        repo: skycoin/services
  - language: go
    go_import_path: github.com/skycoin/services
    go: 1.10.3
    sudo: required
    install: true
    script:
    - cd ./autoupdater
    - go test ./...
    - cd ./cmd/autoupdater
    - go build
    deploy:
    - provider: script
      script:
      - sh $TRAVIS_BUILD_DIR/.travis/deploy.sh
      skip_cleanup: true
      on:
        repo: skycoin/services
