[SKY]
node = "localhost:6430"
seed = "otc"
name = "otc"

[BTC]
node = "localhost:18332"
user = "otc"
pass = "otc"
account = "otc"
testnet = true

[API.Public]
listen = ":8081"

[API.Admin]
listen = ":8080"

[Watcher]
node = "localhost:8888"
