[bitcoin]
BlockExplorer="https://api.blockcypher.com"
WatcherUrl="http://localhost:8081"

[skycoin]
Host="127.0.0.1"
Port="6420"

[server]
ListenStr="0.0.0.0:9090"
ReadTimeout = 5
WriteTimeout = 10
IdleTimeout = 120
