[global]
updater="swarm"

[active]
interval="1h"
tag="latest"
repository="library/mariadb"
name="dockerhub"
service="maria"

[passive]
message-broker="nats"
urls=["url1","url2"]

[[service]]
official_name="skycoin/skycoin"
local_name="library/mariadb"
update_script="./updater/custom_example/custom_script.sh"
script_interpreter="/bin/bash"
script_timeout="5s"
script_extra_arguments=["-a 1"]

[[service]]
official_name="top" 
local_name= "skywire"
update_script="./updater/custom_example/custom_script.sh"
script_interpreter="/bin/bash"
script_timeout="5s"
script_extra_arguments=[""]

[[service]]
official_name="sky-node" 
local_name="skycoin"
update_script="./updater/custom_example/custom_script.sh"
script_interpreter="/bin/bash"
script_timeout="7s"
script_extra_arguments=["-a 1","-b 2"]

[[service]]
official_name="skywire"
local_name="mystack_skywire"
update_script="./updater/custom_example/custom_script.sh"
script_interpreter="/bin/bash"
script_timeout=""
script_extra_arguments=[""]