[bitcoin]
NodeAddress="23.92.24.9:8334"
User="YnWD3EmQAOw11IOrUJwWxAThAyobwLC"
Password='f*Z"[1215o{qKW{Buj/wheO8@h.}j*u'
CertFile="btcd.cert"
TLS=true
BlockExplorer="https://api.blockcypher.com"
BlockDepth=32

[skycoin]
Host="127.0.0.1"
Port="6420"

[server]
ListenStr="0.0.0.0:9090"
ReadTimeout = 5
WriteTimeout = 10
IdleTimeout = 120
