[bitcoin]
NodeAddress="45.33.44.212:8334"
User="TG4zCvPNJWSjkCqHGN3hZLo9Ahk="
Password="cf7trPlnjZOhJtRp+aOIlk8ewF4="
CertFile="btcd.cert"
TLS=true

[skycoin]
Host="0.0.0.0"
Port="9341"

[server]
ListenStr="0.0.0.0:8080"
ReadTimeout = 5
WriteTimeout = 10
IdleTimeout = 120